DROP SCHEMA IF EXISTS AT_CONS_TEST;
CREATE SCHEMA IF NOT EXISTS AT_CONS_TEST;
SET SCHEMA AT_CONS_TEST;

CREATE TABLE USERS (
  ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
  EMAIL    VARCHAR(255) UNIQUE NOT NULL,
  USERNAME VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD VARCHAR(63)
);

CREATE TABLE BOOKS (
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
  ISBN        VARCHAR(120) UNIQUE      NOT NULL,
  TITLE       VARCHAR(120)             NOT NULL,
  AUTHOR_NAME VARCHAR(120)             NOT NULL,
  READER_NAME VARCHAR(120) DEFAULT NULL,
  FOREIGN KEY (READER_NAME) REFERENCES USERS (USERNAME) ON DELETE CASCADE
);

CREATE TABLE USER_ROLES (
  USER_ID BIGINT      NOT NULL,
  ROLE    VARCHAR(60) NOT NULL,
  CONSTRAINT IDX_USER_ROLE UNIQUE (USER_ID, ROLE),
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
);
