CREATE SCHEMA IF NOT EXISTS AT_cons_test;

CREATE TABLE USER (
  ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(255) UNIQUE,
  PASSWORD VARCHAR(63)
);

CREATE TABLE BOOK (
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
  ISBN        VARCHAR(123) UNIQUE      NOT NULL,
  TITLE       VARCHAR(123)             NOT NULL,
  AUTHOR_NAME VARCHAR(123)             NOT NULL,
  USER_ID     BIGINT DEFAULT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
);

CREATE TABLE USER_ROLE (
  USER_ID BIGINT      NOT NULL,
  ROLE    VARCHAR(63) NOT NULL,
  CONSTRAINT IDX_USER_ROLE UNIQUE (USER_ID, ROLE),
  FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
);
